--CREATE DATABASE MinalEshcolot

USE MinalEshcolot

CREATE TABLE  ROOMS(
 ROOM_ID INT  NOT NULL IDENTITY,
 ROOM_NAME NVARCHAR(50),
 ROOM_FLOOR INT,
 ROOM_TFUSA INT,
 ROOM_TYPE int
)


CREATE TABLE EQUIPMENT(
ITEM_ID INT  IDENTITY not null,
ITEM_NAME NVARCHAR(50)
)


CREATE TABLE INLAY(
INLAY_ID INT IDENTITY not null ,
INLAY_DATE DATETIME,
FROM_HOUER DATETIME,
TO_HOUER DATETIME,
USR_ID INT,
ONE_TIME_OR_WEEKLY int,
SEVERAL_SESSIONS INT
)

CREATE TABLE USERS(
USR_ID INT IDENTITY not null,
USR_NAME NVARCHAR(50),
USR_PHONE INT ,
USR_CITY NVARCHAR(50),
USR_ADDRESS NVARCHAR(50)
)

CREATE TABLE INLAY_EQUIPMENT(
INTALY_ID INT,
ITEM_ID INT,
ITEM_COUNT int
)
CREATE TABLE INLAY_ROOMS(
INTALY_ID INT,
ROOM_ID INT
)

CREATE TABLE ROOM_TYPE(
TYPE_ID INT IDENTITY not null,
TYPE_NAME NVARCHAR(50)
)
truncate table [dbo].[INLAY_EQUIPMENT]
